# Dependencies
markdown:         kramdown

# Permalinks
permalink:        /:year/:month/:day/:title/

# Setup
title:            yarsnowing
description:      I Am Free!
url:              http://yarsnowing.me/
domain:           yarsnowing.me
email:            1403946480.com
twitter_username: ztpala
github_username:  yarsnowing
github_repo:      https://github.com/yarsnowing/yarsnowing.github.io
google_analytics: UA-5531632-1
timezone:         America/New_York
subscribe:        http://feed.ztpala.com
baseurl: ""
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - newpost.rb
  - CNAME
