# Dependencies
markdown:         kramdown

# Permalinks
permalink:        /:year/:month/:day/:title/

# Setup
title:            yarsnowing
description:      I Am Free !
url:              http://yarsnowing.me/
domain:           yarsnowing.me
email:            1403946480@qq.com
douban_username:  yarsnowing
zhihu_username:   yarsnowing
github_username:  yarsnowing
github_repo:      https://github.com/yarsnowing/yarsnowing.github.io
google_analytics: UA-5531632-1
timezone:         Asia/Shanghai
subscribe:        http://yarsnowing.me/
baseurl: ""
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - newpost.rb
  - CNAME
